class ExceptionTest 
{
public static void main(String arg[])
{
try{
//ArithmeticException
int a=10/0;
System.out.println("A:"+a);

//NullPointerException
//String  b=null;
//System.out.println("A:"+b.length());

//ArrayIndexOutOfBoundsException
//int a[]={10,20,30};
//System.out.println("A:"+a[5]);

//StringIndexOutOfBoundsException
//String  a="hello";
//System.out.println(a.charAt(6));
}
catch(ArithmeticException e)
{
System.out.println("Exception:"+e.getMessage());
}
catch(NullPointerException e)
{
System.out.println("Exception:"+e.getMessage());
}
catch(ArrayIndexOutOfBoundsException e)
{
System.out.println("Exception:"+e.getMessage());
}
catch(StringIndexOutOfBoundsException e)
{
System.out.println("Exception:"+e.getMessage());
}
System.out.println("program ends");
}
 }